name: ASN.1Chef Editor CI

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 240

    steps:
    - name: Install system dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: pkg-config build-essential libkrb5-dev libx11-dev libxkbfile-dev
        version: 1.0

    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: wasm32-unknown-unknown

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: yarn
        cache-dependency-path: '**/yarn.lock'

    - name: Install Yarn
      run: npm install --global yarn

    - name: Run Tests
      run: make test

    - name: Build VSCode Web
      run: make build-vscode-web

    - name: Archive VSCode Web Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vscode-web
        path: web/vscode-web/dist/
        overwrite: true

    - name: Build Editor
      run: make build-editor

    - name: Archive Editor Artifact
      uses: actions/upload-artifact@v4
      with:
        name: editor
        path: web/editor/dist/
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download Editor Artifact
        uses: actions/download-artifact@v4
        with:
          name: editor
          path: editor

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Editor Artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './editor'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
